### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by friscowarren** [datasets/s-and-p-500-companies#1]
I've tried for three days to download your s and p spreadsheet with data. It seems we are speaking different languages. My idea of easy to use is when you press download and it downloads.  I've tried excel and google docs.  I've read your stuff at the bottom of the page, but none of it makes sense.  I've tried your help page, but I want  help, and not to chat.

**Comment by lexman** [comment]
I'm closing this because the solution seems good to me...
