### ISSUE TITLE
DTV replaced by SIG

### ISSUE THREAD

**Issue by aickley** [datasets/s-and-p-500-companies#10]
DirecTV was bought by AT&T and replaced by SIG in the index
http://www.streetinsider.com/Index+Changes/Signet+Jewelers+(SIG)+to+Replace+DirectTV+(DTV)+in+S%26P+500,+Other+Changes+(PRXL)+(ENTA)+(CTLT)/10751889.html

**Comment by rgrp** [comment]
@aickley would you like to submit a pull request - and include that info :-)

**Comment by rgrp** [comment]
FIXED by #11
