### ISSUE TITLE
Automate data updates with travis

### ISSUE THREAD

**Issue by lexman** [datasets/s-and-p-500-companies#14]
@rgrp my doc on [continuous processing with travis](https://github.com/lexman/ex-continuous-processing) is nearly over, and I'd like this s-and-p-500-companies project to be the pilot.

When I want to add this project to travis I've got this message _You require admin rights to enable these repositories_. Could you either give me admin rights to the repository (I'm not sure what it means) or enable travis to run this project ? Thanks...

**Comment by lexman** [comment]
I'll also need access to the settings of his repo to set the ssh key.

I think you can give admin access to this project for the whole curators team by going to the |list of repositories of the team](https://github.com/orgs/datasets/teams/curators/repositories). There you should find a *settings* link facing project s-and-p-500-companies . In this page you should be able to add me as a collaboraor with 'admin' access instead of 'write access'.

Thanks for help !
cc all the admins : @zelima @pdehaye @sxren

**Comment by zelima** [comment]
@lexman consulting with @rgrp I've just made you owner of an organisation. Now you have admin access rights.
Thanks for help and my congratulations, keep it up! :)

**Comment by lexman** [comment]
It works ! Thank you @zelima !

**Comment by rgrp** [comment]
@lexman how are we doing on automating this - relevant for #17

**Comment by rufuspollock** [comment]
INVALID (FIXED). We have automation via github actions now.
