### ISSUE TITLE
During installation ran into an OSError on OS X 10.11.6

### ISSUE THREAD

**Issue by anujgoyal** [datasets/s-and-p-500-companies#16]
System Version: OS X 10.11.6 (15G31)
Kernel Version: Darwin 15.6.0

> $ pip install -r requirements.txt
> Requirement already satisfied (use --upgrade to upgrade): xlrd==0.9.3 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied (use --upgrade to upgrade): unicodecsv in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
> Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4))
> Collecting datapackage (from -r requirements.txt (line 5))
>   Downloading datapackage-0.8.0.tar.gz
> Collecting goodtables (from -r requirements.txt (line 6))
>   Downloading goodtables-0.7.5.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Library/Python/2.7/site-packages (from jinja2->-r requirements.txt (line 3))
> Collecting six>=1.10.0 (from datapackage->-r requirements.txt (line 5))
>   Downloading six-1.10.0-py2.py3-none-any.whl
> Collecting requests>=2.8.0 (from datapackage->-r requirements.txt (line 5))
>   Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
>     100% |████████████████████████████████| 512kB 1.2MB/s 
> Collecting jsonschema>=2.5.1 (from datapackage->-r requirements.txt (line 5))
>   Downloading jsonschema-2.5.1-py2.py3-none-any.whl
> Collecting tabulator>=0.4.0 (from datapackage->-r requirements.txt (line 5))
>   Downloading tabulator-0.4.0-py2.py3-none-any.whl
> Collecting jsontableschema>=0.5.1 (from datapackage->-r requirements.txt (line 5))
>   Downloading jsontableschema-0.6.5-py2.py3-none-any.whl (41kB)
>     100% |████████████████████████████████| 51kB 9.9MB/s 
> Collecting Click>=3.3 (from goodtables->-r requirements.txt (line 6))
>   Downloading click-6.6.tar.gz (283kB)
>     100% |████████████████████████████████| 286kB 1.5MB/s 
> Collecting cchardet>=1.0.0 (from goodtables->-r requirements.txt (line 6))
>   Downloading cchardet-1.0.0.tar.gz (609kB)
>     100% |████████████████████████████████| 614kB 1.1MB/s 
> Collecting tellme>=0.2.4 (from goodtables->-r requirements.txt (line 6))
>   Downloading tellme-0.2.6.tar.gz
> Collecting functools32; python_version == "2.7" (from jsonschema>=2.5.1->datapackage->-r requirements.txt (line 5))
>   Downloading functools32-3.2.3-2.zip
> Collecting chardet>=2.0 (from tabulator>=0.4.0->datapackage->-r requirements.txt (line 5))
>   Downloading chardet-2.3.0.tar.gz (164kB)
>     100% |████████████████████████████████| 174kB 1.7MB/s 
> Collecting linear-tsv>=0.99.1 (from tabulator>=0.4.0->datapackage->-r requirements.txt (line 5))
>   Downloading linear-tsv-0.99.1.tar.gz
> Collecting openpyxl>=2.0 (from tabulator>=0.4.0->datapackage->-r requirements.txt (line 5))
>   Downloading openpyxl-2.3.5.tar.gz (141kB)
>     100% |████████████████████████████████| 143kB 3.8MB/s 
> Collecting ijson>=2.0 (from tabulator>=0.4.0->datapackage->-r requirements.txt (line 5))
>   Downloading ijson-2.3-py2.py3-none-any.whl
> Collecting python-dateutil>=2.4.0 (from jsontableschema>=0.5.1->datapackage->-r requirements.txt (line 5))
>   Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
>     100% |████████████████████████████████| 204kB 1.7MB/s 
> Collecting rfc3986>=0.3.0 (from jsontableschema>=0.5.1->datapackage->-r requirements.txt (line 5))
>   Downloading rfc3986-0.3.1-py2.py3-none-any.whl
> Collecting future>=0.15.2 (from jsontableschema>=0.5.1->datapackage->-r requirements.txt (line 5))
>   Downloading future-0.15.2.tar.gz (1.6MB)
>     100% |████████████████████████████████| 1.6MB 552kB/s 
> Collecting PyYAML>=3.11 (from tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading PyYAML-3.11.zip (371kB)
>     100% |████████████████████████████████| 378kB 1.4MB/s 
> Collecting dataset>=0.5.5 (from tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading dataset-0.6.4.tar.gz
> Collecting tabulate>=0.7.4 (from tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading tabulate-0.7.5.tar.gz
> Collecting jdcal (from openpyxl>=2.0->tabulator>=0.4.0->datapackage->-r requirements.txt (line 5))
>   Downloading jdcal-1.2.tar.gz
> Collecting et_xmlfile (from openpyxl>=2.0->tabulator>=0.4.0->datapackage->-r requirements.txt (line 5))
>   Downloading et_xmlfile-1.0.1.tar.gz
> Collecting sqlalchemy>=0.9.1 (from dataset>=0.5.5->tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading SQLAlchemy-1.0.14.tar.gz (4.8MB)
>     100% |████████████████████████████████| 4.8MB 237kB/s 
> Collecting alembic>=0.6.2 (from dataset>=0.5.5->tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading alembic-0.8.7.tar.gz (968kB)
>     100% |████████████████████████████████| 972kB 846kB/s 
> Collecting normality>=0.2.2 (from dataset>=0.5.5->tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading normality-0.2.4-py2-none-any.whl
> Collecting Mako (from alembic>=0.6.2->dataset>=0.5.5->tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading Mako-1.0.4.tar.gz (574kB)
>     100% |████████████████████████████████| 583kB 1.1MB/s 
> Collecting python-editor>=0.3 (from alembic>=0.6.2->dataset>=0.5.5->tellme>=0.2.4->goodtables->-r requirements.txt (line 6))
>   Downloading python-editor-1.0.1.tar.gz
> Installing collected packages: six, requests, functools32, jsonschema, chardet, linear-tsv, python-dateutil, rfc3986, future, Click, jsontableschema, jdcal, et-xmlfile, openpyxl, ijson, tabulator, datapackage, cchardet, PyYAML, sqlalchemy, Mako, python-editor, alembic, normality, dataset, tabulate, tellme, goodtables
>   Found existing installation: six 1.4.1
>     DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
>     Uninstalling six-1.4.1:
> Exception:
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
>     prefix=options.prefix_path,
>   File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
>     renames(path, new_path)
>   File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/**init**.py", line 267, in renames
>     shutil.move(old, new)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
>     copy2(src, real_dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
>     copystat(src, dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
>     os.chflags(dst, st.st_flags)
> OSError: [Errno 1] Operation not permitted: '/var/folders/tk/dblrc8gd4cn2kn04khqd10cm0000gp/T/pip-9oMFA8-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by lexman** [comment]
Hello, I'm not familliar with OSX, but it looks like an issue with Python on this plateform. See http://stackoverflow.com/questions/33185147/on-os-x-el-capitan-i-can-not-upgrade-a-python-package-dependent-on-the-six-compa for example. I'm sorry I can't help you more, but if the stackoverflow answer solves the bug, please tell us !

**Comment by rufuspollock** [comment]
INVALID / OBSOLETE.
