### ISSUE TITLE
Remove constituents-financials?

### ISSUE THREAD

**Issue by noahg** [datasets/s-and-p-500-companies#19]
Hello, cool project. I propose that the constituent-financials be removed from this data package. 

The constituents.csv table is useful in its own right, containing symbol, name, and sector. This file currently still builds but the overall makefile is failing for multiple reasons, one of which is that the Yahoo Finance API [seems to have have changed its terms or perhaps is going away altogether.](https://stackoverflow.com/questions/44057580/yahoo-finance-api-changes-2017) which is causing the constituents-financials to fail.

My assumption is that stock quote and other financial data will forever be relegated to depending on free services that should be considered at a minimum as less dependable than the Wikipedia dependence for just the constituents data. 

The financials are useful but they could be appended by a separate data package that validates the financials only.

**Comment by rufuspollock** [comment]
@noahg very good point. My preference here would be to fork this dataset to have a new dataset s-and-p-companies-financials that contains this historical information and which we try to support going forward and this becomes just the list of companies.

wdyt? Input from users is always very welcome!

PS: if you're interested in helping maintain datasets like this you can become part of our core data curator team http://datahub.io/docs/core-data/curators

**Comment by noahg** [comment]
Yes, that makes sense to me. I can keep going on this repo under a new branch, to remove the financials portion. Are you able to fork this and create the s-and-p-companies-financials repo?  I can pick up with that one after finishing this.

**Comment by rufuspollock** [comment]
@Mikanebu can you create a new repo under datasets named `s-and-p-companies-financials` and then clone this repo and repush it to there (that will be the equivalent of forking for our purposes here).

**Comment by Mikanebu** [comment]
@rufuspollock created new repo https://github.com/datasets/s-and-p-companies-financials

**Comment by rufuspollock** [comment]
@noahg are you still up for doing the change here and we keep financials in the separate repo?

**Comment by noahg** [comment]
Yes I am. Sorry for the delay. Got halfway there today. Will hopefully finish up tomorrow. Planning to use "IEX Trading" for the new financials repo.

**Comment by noahg** [comment]
Okay, I submitted a PR to https://github.com/datasets/s-and-p-companies-financials which uses the IEX API. I'm working backwards from the end-point I suppose. Take a look at that and let me know what you think. Then I can get to working on fixing up this one but I want to make sure my approach is what you're looking for. Thanks!

**Comment by Mikanebu** [comment]
@noahg Great! Thanks for your contribution!
