### ISSUE TITLE
Cannot import name 'pipeline'

### ISSUE THREAD

**Issue by linkwb** [datasets/s-and-p-500-companies#23]
Hi everyone,

When I try to make the package, I get the following:

```
python test_data.py
Traceback (most recent call last):
  File "test_data.py", line 10, in <module>
    from goodtables import pipeline as _pipeline
ImportError: cannot import name 'pipeline'
make: *** [valid.txt] Error 1
```

Even after updating goodtables (only installed xlrd-1.1.0), I'm still running into the issue. 

Goodtables version: 1.5.1
Python version: 3.6.4

Anyone else having this problem/know how to fix it?

Thanks

**Comment by rufuspollock** [comment]
@linkwb we haven't encountered this but we are simplifying making the package. Right now you could just run constituents.py. Re-open if you are still having issues.
