### ISSUE TITLE
Not financials

### ISSUE THREAD

**Issue by fulldecent** [datasets/s-and-p-500-companies#29]
This project is advertised as including "associated financials" in the GitHub description and the name at https://datahub.io/core/s-and-p-500-companies#resource-s-and-p-500-companies_zip.

The included data actually is company name, ticker and sector and includes nothing of a quantitative nature.

To reduce confusion and avoid overselling, I recommend to update the two introductions above to remove mention of financials in this data set.

**Comment by rufuspollock** [comment]
@fulldecent thanks and good point - financials are in a separate repo here https://github.com/datasets/s-and-p-500-companies-financials.

**Comment by fulldecent** [comment]
cool, thank you
