### ISSUE TITLE
Is this list still being maintained?

### ISSUE THREAD

**Issue by msingh0101** [datasets/s-and-p-500-companies#31]
I was looking at this list as well as other datasets from datahub.io and notice that alot of them seem to have stopped updating in 2020.  curious if this is still being maintained?

**Comment by rufuspollock** [comment]
@msingh00 we are still seeking to maintain them and welcome community contributions.

**Comment by rufuspollock** [comment]
FIXED. Actively maintaining.

**Comment by LordKa0S** [comment]
@rufuspollock the [CSV on the website](https://datahub.io/core/s-and-p-500-companies/r/constituents.csv) does not match [data/constituents.csv](https://github.com/datasets/s-and-p-500-companies/blob/main/data/constituents.csv)
